import type { Metadata } from "next";

import { Sarabun } from "next/font/google";

import { Navigation } from "@/components/navigation";

import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { cn } from "@/lib/utils";

const sarabun = Sarabun({
	variable: "--font-sarabun",
	subsets: ["latin", "thai"],
	weight: ["400", "700"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html
			lang="en"
			className={cn("h-full", "antialiased", "font-sans", sarabun.variable)}
			suppressHydrationWarning
		>
			<body className="flex min-h-full flex-col">
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<Navigation />
					{children}
				</ThemeProvider>
			</body>
		</html>
	);
}
