export const COUNTRY_MAP: Record<string, string> = {
	ไทย: "th",
	thai: "th",
	thailand: "th",
	พม่า: "mm",
	เมียนมา: "mm",
	myanmar: "mm",
	burma: "mm",
	ลาว: "la",
	laos: "la",
	lao: "la",
	กัมพูชา: "kh",
	เขมร: "kh",
	cambodia: "kh",
	เวียดนาม: "vn",
	vietnam: "vn",
	มาเลเซีย: "my",
	malaysia: "my",
	สิงคโปร์: "sg",
	singapore: "sg",
	อินโดนีเซีย: "id",
	indonesia: "id",
	ฟิลิปปินส์: "ph",
	philippines: "ph",
	บรูไน: "bn",
	brunei: "bn",
	ติมอร์: "tl",
	timor: "tl",
	จีน: "cn",
	china: "cn",
	ไต้หวัน: "tw",
	taiwan: "tw",
	ญี่ปุ่น: "jp",
	japan: "jp",
	เกาหลีใต้: "kr",
	"south korea": "kr",
	korea: "kr",
	เกาหลีเหนือ: "kp",
	"north korea": "kp",
	ฮ่องกง: "hk",
	"hong kong": "hk",
	มาเก๊า: "mo",
	macau: "mo",
	อินเดีย: "in",
	india: "in",
	บังกลาเทศ: "bd",
	bangladesh: "bd",
	ปากีสถาน: "pk",
	pakistan: "pk",
	ศรีลังกา: "lk",
	"sri lanka": "lk",
	เนปาล: "np",
	nepal: "np",
	อัฟกานิสถาน: "af",
	afghanistan: "af",
	อังกฤษ: "gb",
	สหราชอาณาจักร: "gb",
	uk: "gb",
	สหรัฐอเมริกา: "us",
	อเมริกา: "us",
	usa: "us",
};
